/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.costmanagement.v2019_11_01;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;
import java.util.Collection;

/**
 * Defines values for TimeframeType.
 */
public final class ForecastTimeframeType extends ExpandableStringEnum<ForecastTimeframeType> {
    /** Static value MonthToDate for TimeframeType. */
    public static final ForecastTimeframeType MONTH_TO_DATE = fromString("MonthToDate");

    /** Static value BillingMonthToDate for TimeframeType. */
    public static final ForecastTimeframeType BILLING_MONTH_TO_DATE = fromString("BillingMonthToDate");

    /** Static value TheLastMonth for TimeframeType. */
    public static final ForecastTimeframeType THE_LAST_MONTH = fromString("TheLastMonth");

    /** Static value TheLastBillingMonth for TimeframeType. */
    public static final ForecastTimeframeType THE_LAST_BILLING_MONTH = fromString("TheLastBillingMonth");

    /** Static value WeekToDate for TimeframeType. */
    public static final ForecastTimeframeType WEEK_TO_DATE = fromString("WeekToDate");

    /** Static value Custom for TimeframeType. */
    public static final ForecastTimeframeType CUSTOM = fromString("Custom");

    /**
     * Creates or finds a TimeframeType from its string representation.
     * @param name a name to look for
     * @return the corresponding TimeframeType
     */
    @JsonCreator
    public static ForecastTimeframeType fromString(String name) {
        return fromString(name, ForecastTimeframeType.class);
    }

    /**
     * @return known TimeframeType values
     */
    public static Collection<ForecastTimeframeType> values() {
        return values(ForecastTimeframeType.class);
    }
}
